version: '3.3'

services:
  ethereum:
    image: ahester57/test:dev
    deploy:
      replicas: 2
    ports:
      - '8545:8545'
      - '8546:8546'
      - '30311:30311'
      - '30311:30311/udp'
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
    
