version: '3.3'

services:
  ethereum:
    image: ahester57/parity:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8545:8545'
      - '8546:8546'
      - '30311:30311'
      - '30311:30311/udp'
    networks:
      - webnet
  ipfs:
    image: ahester57/ipfs:latest
    ports:
      - "4001:4001"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet:
volumes:
  myvol:
