version: "3.3"

services:
  ethereum:
    image: settlemint/mintnet:latest
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
  net-intelligence-api:
    image: settlemint/eth-net-intelligence-api
    environment:
      CONTACT_DETAILS: i-support@mintnet.com
      INSTANCE_NAME: My awesome Node (add a company name or location)
      LISTENING_PORT: '30311'
      RPC_HOST: ethereum
      RPC_PORT: '8545'
      WS_SECRET: settlemint
      WS_SERVER: wss://stats.mintnet.settlemint.com
    links:
      - ethereum:ethereum
