[parity]
chain = "/etc/mintnet/mintnet.json"
base_path = "/mnt/io.parity.ethereum"

[rpc]
cors = ['all']

[footprint]
tracing = "on"

[misc]
# Logging pattern (`<module>=<level>`, e.g. `own_tx=trace`).
logging = "own_tx=trace,txqueue=trace"
